name: Metrics - OZI-Project/docs
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics-repo-docs:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          filename: github-metrics-repo-docs.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: OZI-Project
          template: repository
          repo: docs
          plugin_lines: yes
          plugin_followup: yes
          config_timezone: America/Chicago
          commits_authoring: rjdbcm
          plugin_languages: yes
          plugin_languages_limit: 3
          plugin_languages_colors: rainbow
          plugin_languages_ignored: text,
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_indepth: yes
          plugin_languages_details: lines, bytes-size, percentage
