name: Metrics - OZI-Project
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-repo-ozi:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          filename: github-metrics-ozi-project.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: OZI-Project
          template: organization
          plugin_lines: yes
          config_timezone: America/Chicago
