name: Metrics - Issue Followup
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 0 * * *"}]
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          user: OZI-Project
          filename: github-metrics-issue-followup.svg
          token: ${{ secrets.METRICS_TOKEN }}
          base: metadata,
          plugin_followup: yes
          plugin_followup_indepth: yes
          config_timezone: America/Chicago
