name: Metrics - OZI-Project
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 * * * *"}]
  workflow_dispatch:
jobs:
  github-metrics-ozi-project:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          filename: github-metrics-ozi-project.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: OZI-Project
          config_timezone: America/Chicago
          plugin_discussions: yes
          plugin_discussions_categories_limit: 8
