name: Metrics
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          # Your GitHub token
          token: ${{ secrets.METRICS_TOKEN }}

          # Options
          user: OZI-Project
          template: classic
          base: activity, community, repositories, metadata
          config_timezone: America/Chicago
          commits_authoring: rjdbcm
          plugin_introduction: yes
          plugin_introduction_title: yes
          plugin_languages: yes
          plugin_languages_indepth: yes
          plugin_languages_colors: github
