name: Metrics - OZI-Project/publish
on:
  # Schedule updates (each hour) 
  schedule: [{cron: "0 * * * *"}]
  # Lines below let you run workflow manually and on each commit
  workflow_dispatch:
  push: {branches: ["master", "main"]}
jobs:
  github-metrics-repo-publish:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@65836723097537a54cd8eb90f61839426b4266b6 # 3.34
        with:
          filename: github-metrics-repo-publish.svg
          token: ${{ secrets.METRICS_TOKEN }}
          user: OZI-Project
          template: repository
          repo: publish
          plugin_lines: yes
          plugin_followup: yes
